
name: Deploy ARM Template
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check modified files
        id: check_files
        run: |
          changed=`git diff --name-only HEAD HEAD~1 | grep "azuredeploy.json" || true`

          if [[ $changed = "azuredeploy.json" ]]; then
            echo "::set-output name=run_job::true"
          else
            echo "::set-output name=run_job::false"
          fi

  deploy:
    name: Deploy template
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP_LOCATION: "northeurope"
      RESOURCE_GROUP_NAME: "wuma-backend"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource (${{ env.RESOURCE_GROUP_NAME }}) group created in ${{ env.RESOURCE_GROUP_LOCATION }}"
          
      - id: deploy_template
        name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          region: ${{ env.RESOURCE_GROUP_LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: azuredeploy.json
          deploymentMode: Complete
          deploymentName: ${{ env.GITHUB_SHA }}
          parameters: functionsAppName=functions-backend
  push:
    name: Push to Functions
    if: always()
    needs: deploy
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: "2.2.402"
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Functions publish profile
        id: publishprofile
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          resourceGroupName: wuma-backend
          appName: functions-backend

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './backend-functions'
          dotnet build --configuration Release --output ./output
          popd

      - name: Deploy Functions
        uses: Azure/functions-action@v1
        with:
          app-name: functions-backend
          package: ./backend-functions/output
          publish-profile: ${{ steps.publishprofile.outputs.profile }}

      - name: Reset Functions publish profile
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          resourceGroupName: wuma-backend
          appName: functions-backend
          reset: true

          
