
name: Deploy ARM Template
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check modified files
        id: check_files
        run: |
          changed=`git diff --name-only HEAD HEAD~1 | grep "azuredeploy.json"`

          if [[ $changed = "azuredeploy.json" ]]; then
            echo "::set-output name=run_job::true"
          else
            echo "::set-output name=run_job::false"
          fi

  deploy:
    name: Deploy template
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP_LOCATION: "northeurope"
      RESOURCE_GROUP_NAME: "wuma-backend"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/CLI@v1
        if: 
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource (${{ env.RESOURCE_GROUP_NAME }}) group created in ${{ env.RESOURCE_GROUP_LOCATION }}"
          
      - id: deploy_template
        name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          region: ${{ env.RESOURCE_GROUP_LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: azuredeploy.json
          deploymentMode: Complete
          deploymentName: ${{ env.GITHUB_SHA }}
        
