# This is a basic workflow to help you get started with Actions

name: Deploy ARM Template

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #Enviroment
    env:
        RESOURCE_GROUP_LOCATION: "northeurope"
        RESOURCE_GROUP_NAME: "wuma-backend"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
            echo "Azure resource (${{ env.RESOURCE_GROUP_NAME }}) group created in ${{ env.RESOURCE_GROUP_LOCATION }}"
          
      - id: deploy_template
        name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the Id of the subscription which should be used, only required for resource Group or Subscription deployments.
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          # Provide the target region, only required for management Group or Subscription deployments.
          region: ${{ env.RESOURCE_GROUP_LOCATION }}
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          # Specify the path or URL to the Azure Resorce Manager template.
          template: azuredeploy.json
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Complete
          # Specifies the name of the resource group deployment to create.
          deploymentName: ${{ env.GITHUB_SHA }}
